//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.06.29 at 04:36:46 PM EDT
//

package com.adfonic.adserver.vhost;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}beaconBaseUrl"/>
 *           &lt;element ref="{}clickBaseUrl"/>
 *           &lt;element ref="{}clickRedirectBaseUrl"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}assetBaseUrl"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "beaconBaseUrl", "clickBaseUrl", "clickRedirectBaseUrl", "assetBaseUrl" })
@XmlRootElement(name = "vhost")
public class Vhost {

    @XmlSchemaType(name = "anyURI")
    protected String beaconBaseUrl;
    @XmlSchemaType(name = "anyURI")
    protected String clickBaseUrl;
    @XmlSchemaType(name = "anyURI")
    protected String clickRedirectBaseUrl;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String assetBaseUrl;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;

    /**
     * Gets the value of the beaconBaseUrl property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getBeaconBaseUrl() {
        return beaconBaseUrl;
    }

    /**
     * Sets the value of the beaconBaseUrl property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setBeaconBaseUrl(String value) {
        this.beaconBaseUrl = value;
    }

    /**
     * Gets the value of the clickRedirectBaseUrl property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getClickRedirectBaseUrl() {
        return clickRedirectBaseUrl;
    }

    /**
     * Sets the value of the clickRedirectBaseUrl property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setClickRedirectBaseUrl(String value) {
        this.clickRedirectBaseUrl = value;
    }

    /**
     * Gets the value of the clickBaseUrl property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getClickBaseUrl() {
        return clickBaseUrl;
    }

    /**
     * Sets the value of the clickBaseUrl property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setClickBaseUrl(String value) {
        this.clickBaseUrl = value;
    }

    /**
     * Gets the value of the assetBaseUrl property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getAssetBaseUrl() {
        return assetBaseUrl;
    }

    /**
     * Sets the value of the assetBaseUrl property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setAssetBaseUrl(String value) {
        this.assetBaseUrl = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     * 
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setName(String value) {
        this.name = value;
    }

}
