insert into ACCOUNT_DETAIL (TRANSACTION_TIME, ACCOUNT_ID, AMOUNT, TAX,
TOTAL, DESCRIPTION, TRANSACTION_TYPE) 
select '2015-04-30 23:59:59', ACCOUNT.ID, -ACCOUNT.BALANCE, 0,
-ACCOUNT.BALANCE, 'Account disabled by administrator', 'FUNDS_OUT'
from
USER inner join COMPANY on COMPANY.ACCOUNT_MANAGER_ID = USER.ID
 inner join PUBLISHER on PUBLISHER.COMPANY_ID = COMPANY.ID
 inner join ACCOUNT on PUBLISHER.ACCOUNT_ID = ACCOUNT.ID
where USER.STATUS = 'DISABLED'
and ACCOUNT.BALANCE > 0;

update ACCOUNT
 inner join PUBLISHER on PUBLISHER.ACCOUNT_ID = ACCOUNT.ID
 inner join COMPANY on COMPANY.ID = PUBLISHER.COMPANY_ID
 inner join USER on COMPANY.ACCOUNT_MANAGER_ID = USER.ID
set BALANCE = 0 where USER.STATUS = 'DISABLED' and ACCOUNT.BALANCE > 0;
