set @startDay := makedate(extract(year from now() - interval 1 month), dayofyear(last_day(now() - interval 2 month) + interval 1 day));
select @startDay;
select COMPANY.ID, ACCOUNT.ID, USER.EMAIL, COMPANY.NAME, USER.FIRST_NAME, USER.LAST_NAME, sum(TOTAL), PAYMENT_OPTIONS.PAYMENT_TYPE, PAYMENT_OPTIONS.PAYMENT_ACCOUNT,
POSTAL_ADDRESS.FIRST_NAME, POSTAL_ADDRESS.LAST_NAME, POSTAL_ADDRESS.ADDRESS1, POSTAL_ADDRESS.ADDRESS2, POSTAL_ADDRESS.CITY, POSTAL_ADDRESS.STATE, POSTAL_ADDRESS.POSTCODE, COUNTRY.NAME 
from ACCOUNT_DETAIL
inner join ACCOUNT on ACCOUNT_ID = ACCOUNT.ID
inner join PUBLISHER on PUBLISHER.ACCOUNT_ID = ACCOUNT.ID
inner join COMPANY on PUBLISHER.COMPANY_ID = COMPANY.ID
inner join USER on USER.COMPANY_ID = COMPANY.ID
left outer join PAYMENT_OPTIONS on COMPANY.PAYMENT_OPTIONS_ID = PAYMENT_OPTIONS.ID
left outer join POSTAL_ADDRESS on PAYMENT_OPTIONS.POSTAL_ADDRESS_ID = POSTAL_ADDRESS.ID
left outer join COUNTRY on POSTAL_ADDRESS.COUNTRY_ID = COUNTRY.ID
where (TRANSACTION_TIME < @startDay or TRANSACTION_TYPE = 'FUNDS_OUT' or TRANSACTION_TYPE = 'FUNDS_ACROSS')
and ACCOUNT_TYPE = 'PUBLISHER'
and USER.STATUS = 'VERIFIED'
and PAYMENT_OPTIONS.PAYMENT_TYPE != 'PAYPAL'
and ACCOUNT.BALANCE > 50
group by ACCOUNT.ID having sum(TOTAL) >= 50
INTO OUTFILE '/tmp/payments.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';

select PAYMENT_OPTIONS.PAYMENT_ACCOUNT, sum(TOTAL), 'USD', COMPANY.ID
from ACCOUNT_DETAIL
inner join ACCOUNT on ACCOUNT_ID = ACCOUNT.ID
inner join PUBLISHER on PUBLISHER.ACCOUNT_ID = ACCOUNT.ID
inner join COMPANY on PUBLISHER.COMPANY_ID = COMPANY.ID
inner join USER on USER.COMPANY_ID = COMPANY.ID
inner join PAYMENT_OPTIONS on COMPANY.PAYMENT_OPTIONS_ID = PAYMENT_OPTIONS.ID
where (TRANSACTION_TIME < @startDay or TRANSACTION_TYPE = 'FUNDS_OUT' or TRANSACTION_TYPE = 'FUNDS_ACROSS')
and ACCOUNT_TYPE = 'PUBLISHER'
and USER.STATUS = 'VERIFIED'
and PAYMENT_OPTIONS.PAYMENT_TYPE = 'PAYPAL'
and ACCOUNT.BALANCE > 50
group by ACCOUNT.ID having sum(TOTAL) >= 50
INTO OUTFILE '/tmp/payments-masspay.csv'
FIELDS TERMINATED BY '\t'
ENCLOSED BY ''
LINES TERMINATED BY '\n';

