select
concat('AD', lpad(COMPANY.ID, 6, '0')) as 'Account Number',
ADVERTISER.ID,
ADVERTISER.NAME,
USER.EMAIL,
ADFONIC_USER.FIRST_NAME,
ADFONIC_USER.LAST_NAME,
ADFONIC_USER.EMAIL
from COMPANY 
inner join ADVERTISER on ADVERTISER.COMPANY_ID = COMPANY.ID
inner join USER on USER.ID = COMPANY.ACCOUNT_MANAGER_ID
inner join ADFONIC_USER on ADVERTISER.SALES_OWNER_ID = ADFONIC_USER.ID
order by COMPANY.ID asc
into outfile '/tmp/sales-owners.csv'
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';
