//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.29 at 04:36:46 PM EDT 
//


package com.adfonic.adserver.vhost;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.adfonic.adserver.vhost package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AssetBaseUrl_QNAME = new QName("", "assetBaseUrl");
    private final static QName _BeaconBaseUrl_QNAME = new QName("", "beaconBaseUrl");
    private final static QName _ClickRedirectBaseUrl_QNAME = new QName("", "clickRedirectBaseUrl");
    private final static QName _ClickBaseUrl_QNAME = new QName("", "clickBaseUrl");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.adfonic.adserver.vhost
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Vhost }
     * 
     */
    public Vhost createVhost() {
        return new Vhost();
    }

    /**
     * Create an instance of {@link Vhosts }
     * 
     */
    public Vhosts createVhosts() {
        return new Vhosts();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "assetBaseUrl")
    public JAXBElement<String> createAssetBaseUrl(String value) {
        return new JAXBElement<String>(_AssetBaseUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beaconBaseUrl")
    public JAXBElement<String> createBeaconBaseUrl(String value) {
        return new JAXBElement<String>(_BeaconBaseUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "clickRedirectBaseUrl")
    public JAXBElement<String> createClickRedirectBaseUrl(String value) {
        return new JAXBElement<String>(_ClickRedirectBaseUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "clickBaseUrl")
    public JAXBElement<String> createClickBaseUrl(String value) {
        return new JAXBElement<String>(_ClickBaseUrl_QNAME, String.class, null, value);
    }

}
