package com.adfonic.tools.beans.session;

import java.io.Serializable;
import java.math.BigDecimal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.adfonic.presentation.account.AccountService;
import com.adfonic.tools.beans.util.GenericAbstractBean;

@Component
@Scope("session")
public class AccountSessionBean extends GenericAbstractBean implements Serializable {

    /**
     * Generated by Eclipse
     */
    private static final long serialVersionUID = 5365663306212232374L;
    
    @Autowired
    AccountService aService;
        
    public AccountSessionBean() {
        super();
    }

    public BigDecimal getBalance(){
        if(getUser().getAdvertiserDto()!=null){
            return aService.getAccountBalance(getUser().getAdvertiserDto());
        }
        else if(getUser().getPublisherDto()!=null){
            return aService.getAccountBalance(getUser().getPublisherDto());
        }
        return new BigDecimal(0);
    }
    
    public Double getAgencyBalance(){
        if(getUser().getCompany()!=null){
            return aService.getAgencyAccountBalance(getUser().getCompany().getId());
        }
        return 0.0;
    }

    @Override
    protected void init() {}

}
