//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.06 at 10:17:13 AM GMT 
//


package com.byyd.vast2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.byyd.vast2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.byyd.vast2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VAST }
     * 
     */
    public VAST createVAST() {
        return new VAST();
    }

    /**
     * Create an instance of {@link NonLinearType }
     * 
     */
    public NonLinearType createNonLinearType() {
        return new NonLinearType();
    }

    /**
     * Create an instance of {@link CompanionType }
     * 
     */
    public CompanionType createCompanionType() {
        return new CompanionType();
    }

    /**
     * Create an instance of {@link VideoClicksType }
     * 
     */
    public VideoClicksType createVideoClicksType() {
        return new VideoClicksType();
    }

    /**
     * Create an instance of {@link TrackingEventsType }
     * 
     */
    public TrackingEventsType createTrackingEventsType() {
        return new TrackingEventsType();
    }

    /**
     * Create an instance of {@link VAST.Ad }
     * 
     */
    public VAST.Ad createVASTAd() {
        return new VAST.Ad();
    }

    /**
     * Create an instance of {@link VAST.Ad.Wrapper }
     * 
     */
    public VAST.Ad.Wrapper createVASTAdWrapper() {
        return new VAST.Ad.Wrapper();
    }

    /**
     * Create an instance of {@link VAST.Ad.Wrapper.Creatives }
     * 
     */
    public VAST.Ad.Wrapper.Creatives createVASTAdWrapperCreatives() {
        return new VAST.Ad.Wrapper.Creatives();
    }

    /**
     * Create an instance of {@link VAST.Ad.Wrapper.Creatives.Creative }
     * 
     */
    public VAST.Ad.Wrapper.Creatives.Creative createVASTAdWrapperCreativesCreative() {
        return new VAST.Ad.Wrapper.Creatives.Creative();
    }

    /**
     * Create an instance of {@link VAST.Ad.Wrapper.Creatives.Creative.Linear }
     * 
     */
    public VAST.Ad.Wrapper.Creatives.Creative.Linear createVASTAdWrapperCreativesCreativeLinear() {
        return new VAST.Ad.Wrapper.Creatives.Creative.Linear();
    }

    /**
     * Create an instance of {@link VAST.Ad.Wrapper.Creatives.Creative.Linear.VideoClicks }
     * 
     */
    public VAST.Ad.Wrapper.Creatives.Creative.Linear.VideoClicks createVASTAdWrapperCreativesCreativeLinearVideoClicks() {
        return new VAST.Ad.Wrapper.Creatives.Creative.Linear.VideoClicks();
    }

    /**
     * Create an instance of {@link VAST.Ad.InLine }
     * 
     */
    public VAST.Ad.InLine createVASTAdInLine() {
        return new VAST.Ad.InLine();
    }

    /**
     * Create an instance of {@link VAST.Ad.InLine.Creatives }
     * 
     */
    public VAST.Ad.InLine.Creatives createVASTAdInLineCreatives() {
        return new VAST.Ad.InLine.Creatives();
    }

    /**
     * Create an instance of {@link VAST.Ad.InLine.Creatives.Creative }
     * 
     */
    public VAST.Ad.InLine.Creatives.Creative createVASTAdInLineCreativesCreative() {
        return new VAST.Ad.InLine.Creatives.Creative();
    }

    /**
     * Create an instance of {@link VAST.Ad.InLine.Creatives.Creative.Linear }
     * 
     */
    public VAST.Ad.InLine.Creatives.Creative.Linear createVASTAdInLineCreativesCreativeLinear() {
        return new VAST.Ad.InLine.Creatives.Creative.Linear();
    }

    /**
     * Create an instance of {@link VAST.Ad.InLine.Creatives.Creative.Linear.MediaFiles }
     * 
     */
    public VAST.Ad.InLine.Creatives.Creative.Linear.MediaFiles createVASTAdInLineCreativesCreativeLinearMediaFiles() {
        return new VAST.Ad.InLine.Creatives.Creative.Linear.MediaFiles();
    }

    /**
     * Create an instance of {@link AdSystemType }
     * 
     */
    public AdSystemType createAdSystemType() {
        return new AdSystemType();
    }

    /**
     * Create an instance of {@link ImpressionType }
     * 
     */
    public ImpressionType createImpressionType() {
        return new ImpressionType();
    }

    /**
     * Create an instance of {@link NonLinearType.StaticResource }
     * 
     */
    public NonLinearType.StaticResource createNonLinearTypeStaticResource() {
        return new NonLinearType.StaticResource();
    }

    /**
     * Create an instance of {@link CompanionType.StaticResource }
     * 
     */
    public CompanionType.StaticResource createCompanionTypeStaticResource() {
        return new CompanionType.StaticResource();
    }

    /**
     * Create an instance of {@link VideoClicksType.ClickThrough }
     * 
     */
    public VideoClicksType.ClickThrough createVideoClicksTypeClickThrough() {
        return new VideoClicksType.ClickThrough();
    }

    /**
     * Create an instance of {@link VideoClicksType.ClickTracking }
     * 
     */
    public VideoClicksType.ClickTracking createVideoClicksTypeClickTracking() {
        return new VideoClicksType.ClickTracking();
    }

    /**
     * Create an instance of {@link VideoClicksType.CustomClick }
     * 
     */
    public VideoClicksType.CustomClick createVideoClicksTypeCustomClick() {
        return new VideoClicksType.CustomClick();
    }

    /**
     * Create an instance of {@link TrackingEventsType.Tracking }
     * 
     */
    public TrackingEventsType.Tracking createTrackingEventsTypeTracking() {
        return new TrackingEventsType.Tracking();
    }

    /**
     * Create an instance of {@link VAST.Ad.Wrapper.Extensions }
     * 
     */
    public VAST.Ad.Wrapper.Extensions createVASTAdWrapperExtensions() {
        return new VAST.Ad.Wrapper.Extensions();
    }

    /**
     * Create an instance of {@link VAST.Ad.Wrapper.Creatives.Creative.CompanionAds }
     * 
     */
    public VAST.Ad.Wrapper.Creatives.Creative.CompanionAds createVASTAdWrapperCreativesCreativeCompanionAds() {
        return new VAST.Ad.Wrapper.Creatives.Creative.CompanionAds();
    }

    /**
     * Create an instance of {@link VAST.Ad.Wrapper.Creatives.Creative.NonLinearAds }
     * 
     */
    public VAST.Ad.Wrapper.Creatives.Creative.NonLinearAds createVASTAdWrapperCreativesCreativeNonLinearAds() {
        return new VAST.Ad.Wrapper.Creatives.Creative.NonLinearAds();
    }

    /**
     * Create an instance of {@link VAST.Ad.Wrapper.Creatives.Creative.Linear.VideoClicks.ClickTracking }
     * 
     */
    public VAST.Ad.Wrapper.Creatives.Creative.Linear.VideoClicks.ClickTracking createVASTAdWrapperCreativesCreativeLinearVideoClicksClickTracking() {
        return new VAST.Ad.Wrapper.Creatives.Creative.Linear.VideoClicks.ClickTracking();
    }

    /**
     * Create an instance of {@link VAST.Ad.InLine.Extensions }
     * 
     */
    public VAST.Ad.InLine.Extensions createVASTAdInLineExtensions() {
        return new VAST.Ad.InLine.Extensions();
    }

    /**
     * Create an instance of {@link VAST.Ad.InLine.Creatives.Creative.CompanionAds }
     * 
     */
    public VAST.Ad.InLine.Creatives.Creative.CompanionAds createVASTAdInLineCreativesCreativeCompanionAds() {
        return new VAST.Ad.InLine.Creatives.Creative.CompanionAds();
    }

    /**
     * Create an instance of {@link VAST.Ad.InLine.Creatives.Creative.NonLinearAds }
     * 
     */
    public VAST.Ad.InLine.Creatives.Creative.NonLinearAds createVASTAdInLineCreativesCreativeNonLinearAds() {
        return new VAST.Ad.InLine.Creatives.Creative.NonLinearAds();
    }

    /**
     * Create an instance of {@link VAST.Ad.InLine.Creatives.Creative.Linear.MediaFiles.MediaFile }
     * 
     */
    public VAST.Ad.InLine.Creatives.Creative.Linear.MediaFiles.MediaFile createVASTAdInLineCreativesCreativeLinearMediaFilesMediaFile() {
        return new VAST.Ad.InLine.Creatives.Creative.Linear.MediaFiles.MediaFile();
    }

}
