#! /usr/bin/perl

$|++;

use strict;
use warnings;
use CGI;
use Digest::MD5 qw(md5_hex);
use JSON;
use LWP::UserAgent;
use HTTP::Request::Common;
use Data::UUID;

my $numArgs = $#ARGV + 1;

my $winMode = 0;
if ($numArgs >= 1 && $ARGV[0] eq "win") {
    $winMode = 1;
}
print "*** Win mode: " . ($winMode ? "ENABLED" : "DISABLED") . "\n";

my $bidRequest;

my $publisherExternalID = "924146eb-ae41-41b1-bacb-4e445faa99a3";

# Nexage Test
#$bidRequest = '{"site":{"sid":99201,"name":"Bidder Test Mobile WEB","pid":98401,"pub":"RTB Bidder Integration Test Publisher","cat":["IAB1"],"keywords":"radiation","page":"http://www.nexage.com","ref":"http://www.iab.net","search":"radiation"},"id":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd","imp":[{"impid":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd-1","h":320,"w":480}],"device":{"ip":"166.137.138.18","country":"USA","carrier":"ATT","ua":"Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_2_1 like Mac OS X; el-gr) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8C148 Safari/6533.18.5","make":"Apple","model":"iPhone","osv":"3.1.2","js":1,"loc":"42.378,-71.227"},"at":2,"user":{"uid":"ASDFJKL","yob":1961,"gender":"F","zip":"02451","country":"USA","keywords":"sports","nex_eth":4,"nex_marital":"M","nex_kids":"N","nex_hhi":75000,"nex_state":"MA","nex_city":"Waltham","nex_dma":"Boston"}}';
#$bidRequest = '{"site":{"sid":"danSite01","name":"Bidder Test Mobile WEB","pid":"danPub01","pub":"RTB Bidder Integration Test Publisher","cat":["IAB1"],"keywords":"radiation","page":"http://www.nexage.com","ref":"http://www.iab.net","search":"radiation"},"id":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd","imp":[{"impid":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd-1","h":50,"w":300}],"device":{"ip":"166.137.138.18","country":"USA","carrier":"ATT","ua":"Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_2_1 like Mac OS X; el-gr) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8C148 Safari/6533.18.5","make":"Apple","model":"iPhone","osv":"3.1.2","js":1,"loc":"42.378,-71.227"},"at":2,"user":{"uid":"0123456789abcdef0123456789abcdef01234567","yob":1961,"gender":"F","zip":"02451","country":"USA","keywords":"sports","nex_eth":4,"nex_marital":"M","nex_kids":"N","nex_hhi":75000,"nex_state":"MA","nex_city":"Waltham","nex_dma":"Boston"}}';
#$bidRequest = '{"site":{"sid":"danSite01","name":"Bidder Test Mobile WEB","pid":"danPub01","pub":"RTB Bidder Integration Test Publisher","cat":["IAB1"],"keywords":"radiation","page":"http://www.nexage.com","ref":"http://www.iab.net","search":"radiation"},"id":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd","imp":[{"impid":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd-1","h":20,"w":120}],"device":{"ip":"166.137.138.18","country":"USA","carrier":"ATT","ua":"Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_2_1 like Mac OS X; el-gr) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8C148 Safari/6533.18.5","make":"Apple","model":"iPhone","osv":"3.1.2","js":1,"loc":"42.378,-71.227"},"at":2}';

# Fotochat
#my $publisherExternalID = "ef6c5428-dd4e-4fce-b2cc-38b1e60177eb";
my $trackingId = "0123456789abcdef0123456789abcdef01234567"; # 40-char iPhone UDID
my $ipAddress= "67.32.183.150"; # home Georgetown, KY
my $userAgent = "Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_0 like Mac OS X; en-us) AppleWebKit/528.18 (KHTML, like Gecko) Version/4.0 Mobile/7A341 Safari/528.16";

#my $rtbPubId = "98401";
#my $rtbAdSpaceId = "99201";

my $rtbPubId = "1744";
my $rtbAdSpaceId = "1574";

$bidRequest = '{"tmax":99999,"site":{"sid":' . $rtbAdSpaceId . ',"pid":' . $rtbPubId . ',"cat":["IAB1","IAB3","IAB5"],"keywords":"hello,world,whatever"},"id":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd","imp":[{"impid":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd-1","h":50,"w":300}],"device":{"ip":"' . $ipAddress . '","ua":"' . $userAgent . '"},"user":{"uid":"' . $trackingId . '","keywords":"douche,bag"}}';

# Test 320x50 getting mapped to 300x50
#$bidRequest = '{"tmax":99999,"site":{"sid":' . $rtbAdSpaceId . ',"pid":' . $rtbPubId . ',"cat":["IAB1","IAB3","IAB5"],"keywords":"hello,world,whatever"},"id":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd","imp":[{"impid":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd-1","h":50,"w":320}],"device":{"ip":"' . $ipAddress . '","ua":"' . $userAgent . '"},"user":{"uid":"' . $trackingId . '","keywords":"douche,bag"}}';

# This blocks anything associated with the IAB9 or IAB19 categories
#$bidRequest = '{"tmax":99999,"site":{"sid":' . $rtbAdSpaceId . ',"pid":' . $rtbPubId . ',"cat":["IAB1","IAB3","IAB5"],"keywords":"hello,world,whatever"},"id":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd","imp":[{"impid":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd-1","h":50,"w":300}],"device":{"ip":"' . $ipAddress . '","ua":"' . $userAgent . '"},"user":{"uid":"' . $trackingId . '","keywords":"douche,bag"},"restrictions":{"bcat":["IAB9","IAB19"]}}';

# This blocks anything from itunes.apple.com
#$bidRequest = '{"tmax":99999,"site":{"sid":' . $rtbAdSpaceId . ',"pid":' . $rtbPubId . ',"cat":["IAB1","IAB3","IAB5"],"keywords":"hello,world,whatever"},"id":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd","imp":[{"impid":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd-1","h":50,"w":300}],"device":{"ip":"' . $ipAddress . '","ua":"' . $userAgent . '"},"user":{"uid":"' . $trackingId . '","keywords":"douche,bag"},"restrictions":{"badv":["itunes.apple.com"]}}';

# This blocks any creative that's text only
#$bidRequest = '{"tmax":99999,"site":{"sid":' . $rtbAdSpaceId . ',"pid":' . $rtbPubId . ',"cat":["IAB1","IAB3","IAB5"],"keywords":"hello,world,whatever"},"id":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd","imp":[{"impid":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd-1","h":50,"w":300,"battr":[12]}],"device":{"ip":"' . $ipAddress . '","ua":"' . $userAgent . '"},"user":{"uid":"' . $trackingId . '","keywords":"douche,bag"}}';

# This blocks banners and any creative that's text only, so it should invoke a warning
#$bidRequest = '{"tmax":99999,"site":{"sid":' . $rtbAdSpaceId . ',"pid":' . $rtbPubId . ',"cat":["IAB1","IAB3","IAB5"],"keywords":"hello,world,whatever"},"id":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd","imp":[{"impid":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd-1","btype":[2],"battr":[12]}],"device":{"ip":"' . $ipAddress . '","ua":"' . $userAgent . '"},"user":{"uid":"' . $trackingId . '","keywords":"douche,bag"}}';

# This blocks any audio creatives
#$bidRequest = '{"tmax":99999,"site":{"sid":' . $rtbAdSpaceId . ',"pid":' . $rtbPubId . ',"cat":["IAB1","IAB3","IAB5"],"keywords":"hello,world,whatever"},"id":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd","imp":[{"impid":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd-1","h":50,"w":300,"battr":[1,2]}],"device":{"ip":"' . $ipAddress . '","ua":"' . $userAgent . '"},"user":{"uid":"' . $trackingId . '","keywords":"douche,bag"}}';

# This specifies w/h and blocks text, should return only image formats
#$bidRequest = '{"tmax":99999,"site":{"sid":' . $rtbAdSpaceId . ',"pid":' . $rtbPubId . ',"cat":["IAB1","IAB3","IAB5"],"keywords":"hello,world,whatever"},"id":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd","imp":[{"impid":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd-1","h":50,"w":300,"btype":[1]}],"device":{"ip":"' . $ipAddress . '","ua":"' . $userAgent . '"},"user":{"uid":"' . $trackingId . '","keywords":"douche,bag"}}';

# This blocks banners, should return only text
#$bidRequest = '{"tmax":99999,"site":{"sid":' . $rtbAdSpaceId . ',"pid":' . $rtbPubId . ',"cat":["IAB1","IAB3","IAB5"],"keywords":"hello,world,whatever"},"id":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd","imp":[{"impid":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd-1","btype":[2]}],"device":{"ip":"' . $ipAddress . '","ua":"' . $userAgent . '"},"user":{"uid":"' . $trackingId . '","keywords":"douche,bag"}}';

# This specifies w/h but blocks banner, should invoke a warning
#$bidRequest = '{"tmax":99999,"site":{"sid":' . $rtbAdSpaceId . ',"pid":' . $rtbPubId . ',"cat":["IAB1","IAB3","IAB5"],"keywords":"hello,world,whatever"},"id":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd","imp":[{"impid":"b4e2c9b8-77df-4fd2-8bad-07c6d789b7fd-1","h":50,"w":300,"btype":[2]}],"device":{"ip":"' . $ipAddress . '","ua":"' . $userAgent . '"},"user":{"uid":"' . $trackingId . '","keywords":"douche,bag"}}';

$bidRequest = '{"tmax":99999,"id":"f176dbd4-c97b-4583-b2c9-2191c77b2ca4","app":{"aid":4370,"name":"The Score - Android","pid":1276,"pub":"Score Media Ventures, Inc.","cat":["IAB9","IAB17"]},"restrictions":{"bcat":["IAB25","IAB26"],"badv":["espn.com","cbs.com","fox.com","nbc.com","si.com","sportsillustrated.com","sportstap.com","sportacular.com","tsn.ca","thesportsnetwork.ca","sportsnet.ca","cbc.ca"]},"imp":[{"impid":"f176dbd4-c97b-4583-b2c9-2191c77b2ca4-1","h":50,"w":320,"btype":[3]}],"device":{"ip":"174.252.86.180","country":"USA","ua":"Mozilla/5.0 (Linux; U; Android 2.2;en-US;ADR6300 Build/FRF91) AppleWebKit/525.10+ (KHTML, like Gecko) Version/3.0.4 Mobile Safari/523.12.2","make":"HTC","model":"Droid Incredible"},"at":2,"user":{"uid":"0ee5056be20e43a66960d7e96c699c7b"}}';

#$bidRequest = '{"tmax":99999,"site":{"sid":5150, "name":"Bebo", "pid":210, "pub":"Bebo", "cat":["IAB9", "IAB14"], "ref":"http://www.bebo.com/m/friends?f=o&"}, "id":"c57fd3f1-7d6d-4b3b-b176-dbacfbb386e5", "imp":[{"impid":"c57fd3f1-7d6d-4b3b-b176-dbacfbb386e5-1", "h":28, "w":168}], "device":{"ip":"207.154.35.246", "country":"USA", "ua":"LGE-LG290C/1.0[TF268435459301115911000000016059396448] UP.Browser/6.2.3.8 (GUI) MMP/2.0", "make":"LG", "model":"290C (TracFone)"}, "at":2, "user":{"uid":"3ff2d9059bd9ec82cbcca2c09f4fe6d0", "gender":"F"}}';

$bidRequest = '{"id":"d98fd6f6-5cac-4e52-a356-bb625bb6065b", "app":{"aid":"7594", "name":"Clapfoot-TankHero-AndroidApp", "pid":"249", "pub":"Clapfoot Games", "cat":["IAB9"]}, "imp":[{"impid":"d98fd6f6-5cac-4e52-a356-bb625bb6065b-1", "h":50, "w":320}], "device":{"ip":"77.118.208.165", "country":"AUT", "carrier":"3", "ua":"Mozilla/5.0 (Linux; U; Android 2.1-update1; de-at; GT-I9000 Build/ECLAIR) AppleWebKit/530.17 (KHTML, like Gecko) Version/4.0 Mobile Safari/530.17", "make":"Samsung", "model":"GT I9000/Galaxy S", "osv":"2.1"}, "at":2, "user":{"uid":"dPOKXRjYQqqWEtTf69SSFg", "keywords":"null", "nex_kids":"N"}}';

#$bidRequest= '{"id":"a34836d7-d741-413f-bef6-2cea26d5e65b","at":2,"imp":[{"impid":"a34836d7-d741-413f-bef6-2cea26d5e65b-1","h":50,"w":320}],"site":{"sid":"2354","name":"Hi5","pid":522,"pub":"hi5 Newtorks, Inc.","cat":["IAB8"],"keywords":"games","page":"http://m.hi5.com/friend/mobile/mail/displayProfileComments.do","ref":"http://m.hi5.com/friend/mobile/home/displayHomePage.do"},"device":{"ip":"206.53.148.177","country":"THA","carrier":"AIS","ua":"BlackBerry8520/5.0.0.681 Profile/MIDP-2.1 Configuration/CLDC-1.1 VendorID/610","make":"RIM","model":"BlackBerry 8520/Curve","os":"RIM","osv":"4.6.1"}}';

#$bidRequest = '{"id":"a34836d7-d741-413f-bef6-2cea26d5e65b","at":2,"imp":[{"impid":"a34836d7-d741-413f-bef6-2cea26d5e65b-1","h":50,"w":320}],"site":{"sid":"2354","name":"Hi5","pid":522,"pub":"hi5 Newtorks, Inc.","cat":["IAB8"],"keywords":"games","page":"http://m.hi5.com/friend/mobile/mail/displayProfileComments.do","ref":"http://m.hi5.com/friend/mobile/home/displayHomePage.do"},"device":{"ip":"206.53.148.177","country":"THA","carrier":"AIS","ua":"BlackBerry8520/5.0.0.681 Profile/MIDP-2.1 Configuration/CLDC-1.1 VendorID/610","make":"RIM","model":"BlackBerry 8520/Curve","os":"RIM","osv":"4.6.1"}}';

my $uuid = new Data::UUID();
my $bidRequestId = $uuid->to_string($uuid->create());

# Parse it just to be sure it's valid json
my $jsonRequest = JSON->new->decode($bidRequest);

print "*** Posting JSON bid request:\n$bidRequest\n";

my $urlBase = "http://localhost:8080/adfonic-adserver";
#$urlBase = "http://byyd.net";
#$urlBase = "http://dc1.byyd.net";
#$urlBase = "http://dc1adserver01";

my $url = $urlBase . "/rtb/bid/" . $publisherExternalID;
print "*** Posting to URL: $url\n";

my $ua = LWP::UserAgent->new;
$ua->timeout(30);
# We want JSON back
#$ua->default_header("Accept" => "application/json");

my $response = $ua->request(POST $url, Content_Type => "application/json", Content => $bidRequest);

print "*** HTTP Status: ".$response->status_line."\n";
#$response->headers->scan(sub { my ($key, $value) = @_; print "*** Response Header: $key: $value\n"; });

my $content = $response->decoded_content;
print "*** Response Content:\n$content\n";

if (!$response->is_success) {
    exit(1);
}

# Parse the JSON response
my $json = JSON->new->decode($content);
if ($json->{"seatbid"}) {
    my $seatbids = $json->{"seatbid"};
    foreach my $seatbid (@$seatbids) {
        my $bids = $seatbid->{"bid"};
        foreach my $bid (@$bids) {
            # There will be a "price" if there was a bid
            if ($bid->{"price"}) {
                print "*** Got bid for \$" . $bid->{"price"} . " for impid=" . $bid->{"impid"} . "\n";
                my $winNoticeUrl = $bid->{"nurl"};
                $winNoticeUrl =~ s/\${AUCTION_PRICE}/$bid->{"price"}/g;
                if ($winMode) {
                    print "*** Hitting win notice URL:\n$winNoticeUrl\n";
                    $response = $ua->get($winNoticeUrl);
                    print "*** HTTP Status: ".$response->status_line."\n";
                    if (!$response->is_success) {
                        exit(1);
                    }
                    $content = $response->decoded_content;
                    print "*** Win notice response:\n$content\n";
                } else {
                    print "*** Win mode disabled, not hitting win notice URL:\n$winNoticeUrl\n";
                }
            } else {
                print "*** No bid\n";
            }
        }
    }
}
