package com.adfonic.adserver.simulation.impl;

import java.io.InputStream;
import java.io.PrintWriter;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.Date;
import java.sql.NClob;
import java.sql.ParameterMetaData;
import java.sql.PreparedStatement;
import java.sql.Ref;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.RowId;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;
import java.util.logging.Logger;

import javax.sql.DataSource;

public class SimulationDataSource implements DataSource {

	@Override
	public PrintWriter getLogWriter() throws SQLException {
		return null;
	}

	@Override
	public void setLogWriter(PrintWriter out) throws SQLException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void setLoginTimeout(int seconds) throws SQLException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public int getLoginTimeout() throws SQLException {
		return 0;
	}

	@Override
	public Logger getParentLogger() throws SQLFeatureNotSupportedException {
		return null;
	}

	@Override
	public <T> T unwrap(Class<T> iface) throws SQLException {
		return null;
	}

	@Override
	public boolean isWrapperFor(Class<?> iface) throws SQLException {
		return false;
	}

	@Override
	public Connection getConnection() throws SQLException {
		return new Connection() {
			
			@Override
			public <T> T unwrap(Class<T> iface) throws SQLException {
				return null;
			}
			
			@Override
			public boolean isWrapperFor(Class<?> iface) throws SQLException {
				return false;
			}
			
			@Override
			public void setTypeMap(Map<String, Class<?>> map) throws SQLException {
			}
			
			@Override
			public void setTransactionIsolation(int level) throws SQLException {
			}
			
			@Override
			public void setSchema(String schema) throws SQLException {
			}
			
			@Override
			public Savepoint setSavepoint(String name) throws SQLException {
				return null;
			}
			
			@Override
			public Savepoint setSavepoint() throws SQLException {
				return null;
			}
			
			@Override
			public void setReadOnly(boolean readOnly) throws SQLException {
				
			}
			
			@Override
			public void setNetworkTimeout(Executor executor, int milliseconds)
					throws SQLException {
				
			}
			
			@Override
			public void setHoldability(int holdability) throws SQLException {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void setClientInfo(String name, String value)
					throws SQLClientInfoException {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void setClientInfo(Properties properties)
					throws SQLClientInfoException {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void setCatalog(String catalog) throws SQLException {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void setAutoCommit(boolean autoCommit) throws SQLException {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void rollback(Savepoint savepoint) throws SQLException {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void rollback() throws SQLException {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void releaseSavepoint(Savepoint savepoint) throws SQLException {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public PreparedStatement prepareStatement(String sql, int resultSetType,
					int resultSetConcurrency, int resultSetHoldability)
					throws SQLException {
				return new MockStatement();
			}
			
			@Override
			public PreparedStatement prepareStatement(String sql, int resultSetType,
					int resultSetConcurrency) throws SQLException {
				// TODO Auto-generated method stub
				return new MockStatement();
			}
			
			@Override
			public PreparedStatement prepareStatement(String sql, String[] columnNames)
					throws SQLException {
				// TODO Auto-generated method stub
				return new MockStatement();
			}
			
			@Override
			public PreparedStatement prepareStatement(String sql, int[] columnIndexes)
					throws SQLException {
				return new MockStatement();
			}
			
			@Override
			public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)
					throws SQLException {
				return new MockStatement();
			}
			
			@Override
			public PreparedStatement prepareStatement(String sql) throws SQLException {
				return new MockStatement();
			}
			
			@Override
			public CallableStatement prepareCall(String sql, int resultSetType,
					int resultSetConcurrency, int resultSetHoldability)
					throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public CallableStatement prepareCall(String sql, int resultSetType,
					int resultSetConcurrency) throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public CallableStatement prepareCall(String sql) throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public String nativeSQL(String sql) throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public boolean isValid(int timeout) throws SQLException {
				// TODO Auto-generated method stub
				return false;
			}
			
			@Override
			public boolean isReadOnly() throws SQLException {
				// TODO Auto-generated method stub
				return false;
			}
			
			@Override
			public boolean isClosed() throws SQLException {
				// TODO Auto-generated method stub
				return false;
			}
			
			@Override
			public SQLWarning getWarnings() throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public Map<String, Class<?>> getTypeMap() throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public int getTransactionIsolation() throws SQLException {
				// TODO Auto-generated method stub
				return 0;
			}
			
			@Override
			public String getSchema() throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public int getNetworkTimeout() throws SQLException {
				// TODO Auto-generated method stub
				return 0;
			}
			
			@Override
			public DatabaseMetaData getMetaData() throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public int getHoldability() throws SQLException {
				// TODO Auto-generated method stub
				return 0;
			}
			
			@Override
			public String getClientInfo(String name) throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public Properties getClientInfo() throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public String getCatalog() throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public boolean getAutoCommit() throws SQLException {
				// TODO Auto-generated method stub
				return false;
			}
			
			@Override
			public Struct createStruct(String typeName, Object[] attributes)
					throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public Statement createStatement(int resultSetType,
					int resultSetConcurrency, int resultSetHoldability)
					throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public Statement createStatement(int resultSetType, int resultSetConcurrency)
					throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public Statement createStatement() throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public SQLXML createSQLXML() throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public NClob createNClob() throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public Clob createClob() throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public Blob createBlob() throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public Array createArrayOf(String typeName, Object[] elements)
					throws SQLException {
				// TODO Auto-generated method stub
				return null;
			}
			
			@Override
			public void commit() throws SQLException {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void close() throws SQLException {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void clearWarnings() throws SQLException {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void abort(Executor executor) throws SQLException {
				// TODO Auto-generated method stub
				
			}
		};
	}

	@Override
	public Connection getConnection(String username, String password)
			throws SQLException {
		return null;
	}

	public class MockStatement implements PreparedStatement {

		@Override
		public ResultSet executeQuery(String sql) throws SQLException {
			// TODO Auto-generated method stub
			return null;
		}

		@Override
		public int executeUpdate(String sql) throws SQLException {
			// TODO Auto-generated method stub
			return 0;
		}

		@Override
		public void close() throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public int getMaxFieldSize() throws SQLException {
			// TODO Auto-generated method stub
			return 0;
		}

		@Override
		public void setMaxFieldSize(int max) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public int getMaxRows() throws SQLException {
			// TODO Auto-generated method stub
			return 0;
		}

		@Override
		public void setMaxRows(int max) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setEscapeProcessing(boolean enable) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public int getQueryTimeout() throws SQLException {
			// TODO Auto-generated method stub
			return 0;
		}

		@Override
		public void setQueryTimeout(int seconds) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void cancel() throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public SQLWarning getWarnings() throws SQLException {
			// TODO Auto-generated method stub
			return null;
		}

		@Override
		public void clearWarnings() throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setCursorName(String name) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public boolean execute(String sql) throws SQLException {
			// TODO Auto-generated method stub
			return false;
		}

		@Override
		public ResultSet getResultSet() throws SQLException {
			return new ResultSet() {
				
				@Override
				public <T> T unwrap(Class<T> iface) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public boolean isWrapperFor(Class<?> iface) throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
				
				@Override
				public boolean wasNull() throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
				
				@Override
				public void updateTimestamp(String columnLabel, Timestamp x)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateTimestamp(int columnIndex, Timestamp x)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateTime(String columnLabel, Time x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateTime(int columnIndex, Time x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateString(String columnLabel, String x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateString(int columnIndex, String x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateShort(String columnLabel, short x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateShort(int columnIndex, short x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateSQLXML(String columnLabel, SQLXML xmlObject)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateSQLXML(int columnIndex, SQLXML xmlObject)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateRowId(String columnLabel, RowId x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateRowId(int columnIndex, RowId x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateRow() throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateRef(String columnLabel, Ref x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateRef(int columnIndex, Ref x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateObject(String columnLabel, Object x, int scaleOrLength)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateObject(int columnIndex, Object x, int scaleOrLength)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateObject(String columnLabel, Object x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateObject(int columnIndex, Object x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateNull(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateNull(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateNString(String columnLabel, String nString)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateNString(int columnIndex, String nString)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateNClob(String columnLabel, Reader reader, long length)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateNClob(int columnIndex, Reader reader, long length)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateNClob(String columnLabel, Reader reader)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateNClob(int columnIndex, Reader reader) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateNClob(String columnLabel, NClob nClob)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateNClob(int columnIndex, NClob nClob) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateNCharacterStream(String columnLabel, Reader reader,
						long length) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateNCharacterStream(int columnIndex, Reader x, long length)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateNCharacterStream(String columnLabel, Reader reader)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateNCharacterStream(int columnIndex, Reader x)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateLong(String columnLabel, long x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateLong(int columnIndex, long x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateInt(String columnLabel, int x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateInt(int columnIndex, int x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateFloat(String columnLabel, float x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateFloat(int columnIndex, float x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateDouble(String columnLabel, double x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateDouble(int columnIndex, double x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateDate(String columnLabel, Date x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateDate(int columnIndex, Date x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateClob(String columnLabel, Reader reader, long length)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateClob(int columnIndex, Reader reader, long length)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateClob(String columnLabel, Reader reader)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateClob(int columnIndex, Reader reader) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateClob(String columnLabel, Clob x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateClob(int columnIndex, Clob x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateCharacterStream(String columnLabel, Reader reader,
						long length) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateCharacterStream(int columnIndex, Reader x, long length)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateCharacterStream(String columnLabel, Reader reader,
						int length) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateCharacterStream(int columnIndex, Reader x, int length)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateCharacterStream(String columnLabel, Reader reader)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateCharacterStream(int columnIndex, Reader x)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBytes(String columnLabel, byte[] x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBytes(int columnIndex, byte[] x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateByte(String columnLabel, byte x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateByte(int columnIndex, byte x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBoolean(String columnLabel, boolean x)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBoolean(int columnIndex, boolean x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBlob(String columnLabel, InputStream inputStream,
						long length) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBlob(int columnIndex, InputStream inputStream, long length)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBlob(String columnLabel, InputStream inputStream)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBlob(int columnIndex, InputStream inputStream)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBlob(String columnLabel, Blob x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBlob(int columnIndex, Blob x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBinaryStream(String columnLabel, InputStream x,
						long length) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBinaryStream(int columnIndex, InputStream x, long length)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBinaryStream(String columnLabel, InputStream x, int length)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBinaryStream(int columnIndex, InputStream x, int length)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBinaryStream(String columnLabel, InputStream x)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBinaryStream(int columnIndex, InputStream x)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBigDecimal(String columnLabel, BigDecimal x)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateBigDecimal(int columnIndex, BigDecimal x)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateAsciiStream(String columnLabel, InputStream x, long length)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateAsciiStream(int columnIndex, InputStream x, long length)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateAsciiStream(String columnLabel, InputStream x, int length)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateAsciiStream(int columnIndex, InputStream x, int length)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateAsciiStream(String columnLabel, InputStream x)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateAsciiStream(int columnIndex, InputStream x)
						throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateArray(String columnLabel, Array x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void updateArray(int columnIndex, Array x) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void setFetchSize(int rows) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void setFetchDirection(int direction) throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public boolean rowUpdated() throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
				
				@Override
				public boolean rowInserted() throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
				
				@Override
				public boolean rowDeleted() throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
				
				@Override
				public boolean relative(int rows) throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
				
				@Override
				public void refreshRow() throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public boolean previous() throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
				
				@Override
				public boolean next() throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
				
				@Override
				public void moveToInsertRow() throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void moveToCurrentRow() throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public boolean last() throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
				
				@Override
				public boolean isLast() throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
				
				@Override
				public boolean isFirst() throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
				
				@Override
				public boolean isClosed() throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
				
				@Override
				public boolean isBeforeFirst() throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
				
				@Override
				public boolean isAfterLast() throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
				
				@Override
				public void insertRow() throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public SQLWarning getWarnings() throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public InputStream getUnicodeStream(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public InputStream getUnicodeStream(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public URL getURL(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public URL getURL(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public int getType() throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public Timestamp getTimestamp(String columnLabel, Calendar cal)
						throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Timestamp getTimestamp(int columnIndex, Calendar cal)
						throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Timestamp getTimestamp(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Timestamp getTimestamp(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Time getTime(String columnLabel, Calendar cal) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Time getTime(int columnIndex, Calendar cal) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Time getTime(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Time getTime(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public String getString(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public String getString(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Statement getStatement() throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public short getShort(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public short getShort(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public SQLXML getSQLXML(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public SQLXML getSQLXML(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public RowId getRowId(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public RowId getRowId(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public int getRow() throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public Ref getRef(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Ref getRef(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public <T> T getObject(String columnLabel, Class<T> type)
						throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public <T> T getObject(int columnIndex, Class<T> type) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Object getObject(String columnLabel, Map<String, Class<?>> map)
						throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Object getObject(int columnIndex, Map<String, Class<?>> map)
						throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Object getObject(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Object getObject(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public String getNString(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public String getNString(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public NClob getNClob(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public NClob getNClob(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Reader getNCharacterStream(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Reader getNCharacterStream(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public ResultSetMetaData getMetaData() throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public long getLong(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public long getLong(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public int getInt(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public int getInt(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public int getHoldability() throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public float getFloat(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public float getFloat(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public int getFetchSize() throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public int getFetchDirection() throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public double getDouble(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public double getDouble(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public Date getDate(String columnLabel, Calendar cal) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Date getDate(int columnIndex, Calendar cal) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Date getDate(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Date getDate(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public String getCursorName() throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public int getConcurrency() throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public Clob getClob(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Clob getClob(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Reader getCharacterStream(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Reader getCharacterStream(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public byte[] getBytes(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public byte[] getBytes(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public byte getByte(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public byte getByte(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public boolean getBoolean(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
				
				@Override
				public boolean getBoolean(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
				
				@Override
				public Blob getBlob(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Blob getBlob(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public InputStream getBinaryStream(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public InputStream getBinaryStream(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public BigDecimal getBigDecimal(String columnLabel, int scale)
						throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public BigDecimal getBigDecimal(int columnIndex, int scale)
						throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public BigDecimal getBigDecimal(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public BigDecimal getBigDecimal(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public InputStream getAsciiStream(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public InputStream getAsciiStream(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Array getArray(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public Array getArray(int columnIndex) throws SQLException {
					// TODO Auto-generated method stub
					return null;
				}
				
				@Override
				public boolean first() throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
				
				@Override
				public int findColumn(String columnLabel) throws SQLException {
					// TODO Auto-generated method stub
					return 0;
				}
				
				@Override
				public void deleteRow() throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void close() throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void clearWarnings() throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void cancelRowUpdates() throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void beforeFirst() throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public void afterLast() throws SQLException {
					// TODO Auto-generated method stub
					
				}
				
				@Override
				public boolean absolute(int row) throws SQLException {
					// TODO Auto-generated method stub
					return false;
				}
			};
		}

		@Override
		public int getUpdateCount() throws SQLException {
			// TODO Auto-generated method stub
			return 0;
		}

		@Override
		public boolean getMoreResults() throws SQLException {
			// TODO Auto-generated method stub
			return false;
		}

		@Override
		public void setFetchDirection(int direction) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public int getFetchDirection() throws SQLException {
			// TODO Auto-generated method stub
			return 0;
		}

		@Override
		public void setFetchSize(int rows) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public int getFetchSize() throws SQLException {
			// TODO Auto-generated method stub
			return 0;
		}

		@Override
		public int getResultSetConcurrency() throws SQLException {
			// TODO Auto-generated method stub
			return 0;
		}

		@Override
		public int getResultSetType() throws SQLException {
			// TODO Auto-generated method stub
			return 0;
		}

		@Override
		public void addBatch(String sql) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void clearBatch() throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public int[] executeBatch() throws SQLException {
			// TODO Auto-generated method stub
			return null;
		}

		@Override
		public Connection getConnection() throws SQLException {
			// TODO Auto-generated method stub
			return null;
		}

		@Override
		public boolean getMoreResults(int current) throws SQLException {
			// TODO Auto-generated method stub
			return false;
		}

		@Override
		public ResultSet getGeneratedKeys() throws SQLException {
			// TODO Auto-generated method stub
			return null;
		}

		@Override
		public int executeUpdate(String sql, int autoGeneratedKeys)
				throws SQLException {
			// TODO Auto-generated method stub
			return 0;
		}

		@Override
		public int executeUpdate(String sql, int[] columnIndexes)
				throws SQLException {
			// TODO Auto-generated method stub
			return 0;
		}

		@Override
		public int executeUpdate(String sql, String[] columnNames)
				throws SQLException {
			// TODO Auto-generated method stub
			return 0;
		}

		@Override
		public boolean execute(String sql, int autoGeneratedKeys)
				throws SQLException {
			// TODO Auto-generated method stub
			return false;
		}

		@Override
		public boolean execute(String sql, int[] columnIndexes)
				throws SQLException {
			// TODO Auto-generated method stub
			return false;
		}

		@Override
		public boolean execute(String sql, String[] columnNames)
				throws SQLException {
			// TODO Auto-generated method stub
			return false;
		}

		@Override
		public int getResultSetHoldability() throws SQLException {
			// TODO Auto-generated method stub
			return 0;
		}

		@Override
		public boolean isClosed() throws SQLException {
			// TODO Auto-generated method stub
			return false;
		}

		@Override
		public void setPoolable(boolean poolable) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public boolean isPoolable() throws SQLException {
			// TODO Auto-generated method stub
			return false;
		}

		@Override
		public void closeOnCompletion() throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public boolean isCloseOnCompletion() throws SQLException {
			// TODO Auto-generated method stub
			return false;
		}

		@Override
		public <T> T unwrap(Class<T> iface) throws SQLException {
			// TODO Auto-generated method stub
			return null;
		}

		@Override
		public boolean isWrapperFor(Class<?> iface) throws SQLException {
			// TODO Auto-generated method stub
			return false;
		}

		@Override
		public ResultSet executeQuery() throws SQLException {
			// TODO Auto-generated method stub
			return null;
		}

		@Override
		public int executeUpdate() throws SQLException {
			// TODO Auto-generated method stub
			return 0;
		}

		@Override
		public void setNull(int parameterIndex, int sqlType)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setBoolean(int parameterIndex, boolean x)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setByte(int parameterIndex, byte x) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setShort(int parameterIndex, short x) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setInt(int parameterIndex, int x) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setLong(int parameterIndex, long x) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setFloat(int parameterIndex, float x) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setDouble(int parameterIndex, double x) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setBigDecimal(int parameterIndex, BigDecimal x)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setString(int parameterIndex, String x) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setBytes(int parameterIndex, byte[] x) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setDate(int parameterIndex, Date x) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setTime(int parameterIndex, Time x) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setTimestamp(int parameterIndex, Timestamp x)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setAsciiStream(int parameterIndex, InputStream x, int length)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setUnicodeStream(int parameterIndex, InputStream x,
				int length) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setBinaryStream(int parameterIndex, InputStream x,
				int length) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void clearParameters() throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setObject(int parameterIndex, Object x, int targetSqlType)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setObject(int parameterIndex, Object x) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public boolean execute() throws SQLException {
			// TODO Auto-generated method stub
			return false;
		}

		@Override
		public void addBatch() throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setCharacterStream(int parameterIndex, Reader reader,
				int length) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setRef(int parameterIndex, Ref x) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setBlob(int parameterIndex, Blob x) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setClob(int parameterIndex, Clob x) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setArray(int parameterIndex, Array x) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public ResultSetMetaData getMetaData() throws SQLException {
			// TODO Auto-generated method stub
			return null;
		}

		@Override
		public void setDate(int parameterIndex, Date x, Calendar cal)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setTime(int parameterIndex, Time x, Calendar cal)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setTimestamp(int parameterIndex, Timestamp x, Calendar cal)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setNull(int parameterIndex, int sqlType, String typeName)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setURL(int parameterIndex, URL x) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public ParameterMetaData getParameterMetaData() throws SQLException {
			// TODO Auto-generated method stub
			return null;
		}

		@Override
		public void setRowId(int parameterIndex, RowId x) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setNString(int parameterIndex, String value)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setNCharacterStream(int parameterIndex, Reader value,
				long length) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setNClob(int parameterIndex, NClob value)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setClob(int parameterIndex, Reader reader, long length)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setBlob(int parameterIndex, InputStream inputStream,
				long length) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setNClob(int parameterIndex, Reader reader, long length)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setSQLXML(int parameterIndex, SQLXML xmlObject)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setObject(int parameterIndex, Object x, int targetSqlType,
				int scaleOrLength) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setAsciiStream(int parameterIndex, InputStream x,
				long length) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setBinaryStream(int parameterIndex, InputStream x,
				long length) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setCharacterStream(int parameterIndex, Reader reader,
				long length) throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setAsciiStream(int parameterIndex, InputStream x)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setBinaryStream(int parameterIndex, InputStream x)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setCharacterStream(int parameterIndex, Reader reader)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setNCharacterStream(int parameterIndex, Reader value)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setClob(int parameterIndex, Reader reader)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setBlob(int parameterIndex, InputStream inputStream)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}

		@Override
		public void setNClob(int parameterIndex, Reader reader)
				throws SQLException {
			// TODO Auto-generated method stub
			
		}
		
	}
}
