//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 05:50:54 PM GMT 
//


package com.byyd.smaato;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="textAd" type="{}textAd"/>
 *         &lt;element name="imageAd" type="{}imageAd"/>
 *         &lt;element name="richmediaAd" type="{}richmediaAd"/>
 *       &lt;/choice>
 *       &lt;attribute name="modelVersion" use="required" type="{}currentModelVersion" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "textAd",
    "imageAd",
    "richmediaAd"
})
@XmlRootElement(name = "ad")
public class Ad {

    protected TextAd textAd;
    protected ImageAd imageAd;
    protected RichmediaAd richmediaAd;
    @XmlAttribute(name = "modelVersion", required = true)
    protected String modelVersion;

    /**
     * Gets the value of the textAd property.
     * 
     * @return
     *     possible object is
     *     {@link TextAd }
     *     
     */
    public TextAd getTextAd() {
        return textAd;
    }

    /**
     * Sets the value of the textAd property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextAd }
     *     
     */
    public void setTextAd(TextAd value) {
        this.textAd = value;
    }

    /**
     * Gets the value of the imageAd property.
     * 
     * @return
     *     possible object is
     *     {@link ImageAd }
     *     
     */
    public ImageAd getImageAd() {
        return imageAd;
    }

    /**
     * Sets the value of the imageAd property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageAd }
     *     
     */
    public void setImageAd(ImageAd value) {
        this.imageAd = value;
    }

    /**
     * Gets the value of the richmediaAd property.
     * 
     * @return
     *     possible object is
     *     {@link RichmediaAd }
     *     
     */
    public RichmediaAd getRichmediaAd() {
        return richmediaAd;
    }

    /**
     * Sets the value of the richmediaAd property.
     * 
     * @param value
     *     allowed object is
     *     {@link RichmediaAd }
     *     
     */
    public void setRichmediaAd(RichmediaAd value) {
        this.richmediaAd = value;
    }

    /**
     * Gets the value of the modelVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelVersion() {
        return modelVersion;
    }

    /**
     * Sets the value of the modelVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelVersion(String value) {
        this.modelVersion = value;
    }

}
