//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 05:50:54 PM GMT 
//


package com.byyd.smaato;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.byyd.smaato package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ClickUrl_QNAME = new QName("", "clickUrl");
    private final static QName _ImgUrl_QNAME = new QName("", "imgUrl");
    private final static QName _Beacon_QNAME = new QName("", "beacon");
    private final static QName _AdditionalText_QNAME = new QName("", "additionalText");
    private final static QName _Width_QNAME = new QName("", "width");
    private final static QName _ToolTip_QNAME = new QName("", "toolTip");
    private final static QName _ClickText_QNAME = new QName("", "clickText");
    private final static QName _Content_QNAME = new QName("", "content");
    private final static QName _Height_QNAME = new QName("", "height");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.byyd.smaato
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ad }
     * 
     */
    public Ad createAd() {
        return new Ad();
    }

    /**
     * Create an instance of {@link TextAd }
     * 
     */
    public TextAd createTextAd() {
        return new TextAd();
    }

    /**
     * Create an instance of {@link ImageAd }
     * 
     */
    public ImageAd createImageAd() {
        return new ImageAd();
    }

    /**
     * Create an instance of {@link RichmediaAd }
     * 
     */
    public RichmediaAd createRichmediaAd() {
        return new RichmediaAd();
    }

    /**
     * Create an instance of {@link Beacons }
     * 
     */
    public Beacons createBeacons() {
        return new Beacons();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "clickUrl")
    public JAXBElement<String> createClickUrl(String value) {
        return new JAXBElement<String>(_ClickUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "imgUrl")
    public JAXBElement<String> createImgUrl(String value) {
        return new JAXBElement<String>(_ImgUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "beacon")
    public JAXBElement<String> createBeacon(String value) {
        return new JAXBElement<String>(_Beacon_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "additionalText")
    public JAXBElement<String> createAdditionalText(String value) {
        return new JAXBElement<String>(_AdditionalText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "width")
    public JAXBElement<BigInteger> createWidth(BigInteger value) {
        return new JAXBElement<BigInteger>(_Width_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "toolTip")
    public JAXBElement<String> createToolTip(String value) {
        return new JAXBElement<String>(_ToolTip_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "clickText")
    public JAXBElement<String> createClickText(String value) {
        return new JAXBElement<String>(_ClickText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "content")
    public JAXBElement<String> createContent(String value) {
        return new JAXBElement<String>(_Content_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "height")
    public JAXBElement<BigInteger> createHeight(BigInteger value) {
        return new JAXBElement<BigInteger>(_Height_QNAME, BigInteger.class, null, value);
    }

}
