//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.30 at 05:50:54 PM GMT 
//


package com.byyd.smaato;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for textAd complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="textAd">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}clickText"/>
 *         &lt;element ref="{}clickUrl"/>
 *         &lt;element ref="{}additionalText" minOccurs="0"/>
 *         &lt;element ref="{}toolTip" minOccurs="0"/>
 *         &lt;element name="beacons" type="{}beacons" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "textAd", propOrder = {

})
public class TextAd {

    @XmlElement(required = true)
    protected String clickText;
    @XmlElement(required = true)
    protected String clickUrl;
    protected String additionalText;
    protected String toolTip;
    protected Beacons beacons;

    /**
     * Gets the value of the clickText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClickText() {
        return clickText;
    }

    /**
     * Sets the value of the clickText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClickText(String value) {
        this.clickText = value;
    }

    /**
     * Gets the value of the clickUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClickUrl() {
        return clickUrl;
    }

    /**
     * Sets the value of the clickUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClickUrl(String value) {
        this.clickUrl = value;
    }

    /**
     * Gets the value of the additionalText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalText() {
        return additionalText;
    }

    /**
     * Sets the value of the additionalText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalText(String value) {
        this.additionalText = value;
    }

    /**
     * Gets the value of the toolTip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToolTip() {
        return toolTip;
    }

    /**
     * Sets the value of the toolTip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToolTip(String value) {
        this.toolTip = value;
    }

    /**
     * Gets the value of the beacons property.
     * 
     * @return
     *     possible object is
     *     {@link Beacons }
     *     
     */
    public Beacons getBeacons() {
        return beacons;
    }

    /**
     * Sets the value of the beacons property.
     * 
     * @param value
     *     allowed object is
     *     {@link Beacons }
     *     
     */
    public void setBeacons(Beacons value) {
        this.beacons = value;
    }

}
